systemMessage: "Welcome to the Chocolatine-Powered Marvin Jenkins Instance."

users:
  - id: chocolateen
    password: ${USER_CHOCOLATEEN_PASSWORD}
    name: Hugo
  - id: vaugie_g
    password: ${USER_VAUGIE_G_PASSWORD}
    name: Garance
  - id: i_dont_know
    password: ${USER_I_DONT_KNOW_PASSWORD}
    name: Jeremy
  - id: nasso
    password: ${USER_NASSO_PASSWORD}
    name: Nassim

authorizationStrategy:
  roleBased:
    roles:
      - name: admin
        description: "Marvin master"
        permissions:
          - "Overall/Administer"
        assigned:
          - "chocolateen"
      - name: ape
        description: "Pedagogical team member"
        permissions:
          - "Job/Build"
          - "Workspace/Read"
        assigned:
          - "i_dont_know"
      - name: gorilla
        description: "Group Obsessively Researching Innovation Linked to Learning and Accomplishment"
        permissions:
          - "Job/Build"
          - "Job/Configure"
          - "Job/Create"
          - "Job/Delete"
          - "Job/Move"
          - "Job/Cancel"
          - "Workspace/Read"
        assigned:
          - "vaugie_g"
      - name: assist
        description: "Assistant"
        permissions:
          - "Job/Read"
          - "Workspace/Read"
        assigned:
          - "nasso"

folders:
  - name: "Tools"
    description: "Folder for miscellaneous tools."
    displayName: "Tools"

jobs:
  - name: "clone-repository"
    displayName: "clone-repository"
    folder: "Tools"
    projectType: "freestyle"
    gitUrl: "${GIT_REPOSITORY_URL}"
    cleanWorkspace: true
    executeConcurrently: false
    executeManually: true
    buildCommands:
      - "rm -rf *"
      - "git clone ${GIT_REPOSITORY_URL} ."

  - name: "SEED"
    displayName: "SEED"
    folder: "Tools"
    projectType: "freestyle"
    parameters:
      - name: "GITHUB_NAME"
        description: "GitHub repository owner/repo_name (e.g.: EpitechIT31000/chocolatine)"
        defaultValue: ""
      - name: "DISPLAY_NAME"
        description: "Display name for the job"
        defaultValue: ""
    cleanWorkspace: true
    executeConcurrently: false
    executeManually: true
    scriptPath: "job_dsl.groovy"
